
#server:
#  tomcat:
#    threads:
#      max:  25
#    accept-count: 25

#server.undertow.worker-threads
#server.jetty.acceptors

nom:
  aob:
    sbbench:
      logstring: "Log String 12"
#
#management:
#  endpoint:
#    health:
#      probes:
#        enabled: true

management:
  health:
    probes:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true

elasticsearch:
  url: "192.168.56.101:31200"
## change management.health.probes.enabled to below, after moving to spring-boot version >= 2.3.2 :
#  management.endpoint.health.probes.enabled=true
#  management.health.livenessState.enabled=true
#  management.health.readinessState.enabled=true