apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: actuator-prometheus
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      scrape: actuator-prometheus
  namespaceSelector:
    matchNames:
      - minis
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scheme: http
